id: ADF355495
title: Toh_730-Dh%C4%81ra%E1%B9%87%C4%AB_T%C4%81r%C4%81%E2%80%99s_Own_Promise-v2
type: translation
pechas:
- I287F95DD
- IFCE6A1BE
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-094-007
  eft-text-version: 1.1.8 2021
  title: Toh_730-Dh%C4%81ra%E1%B9%87%C4%AB_T%C4%81r%C4%81%E2%80%99s_Own_Promise-v2
alignment_to_base:
  I287F95DD/E86C: EAB8
  IFCE6A1BE/A97A: EAB8
